"""Add chat_metadata column

Revision ID: 2fa812c8d3b7
Revises: e3f249eef006
Create Date: 2024-11-12 16:03:51.284599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fa812c8d3b7'
down_revision = 'e3f249eef006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_snippet', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chat_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('chat_metadata')
        batch_op.drop_column('code_snippet')

    # ### end Alembic commands ###
